import typer
from rich.console import Console
from pathlib import Path

console = Console()

def init():
    """Installs local pre-push Git Hooks for automated Shift-Left governance"""
    
    git_dir = Path(".git")
    if not git_dir.exists():
        console.print("[red]❌ Error:[/red] '.git' directory was not found.")
        console.print("[yellow]💡 Hint:[/yellow] Run this command at the root folder of an initialized Git repository (`git init`).")
        raise typer.Exit(code=1)
    
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True) 
    
    hook_file = hooks_dir / "pre-push"
    
    hook_content = """#!/bin/sh
        # Automatically generated by DevEx Golden Path CLI

        echo "==> [DevEx Platform] Triggering Shift-Left validations before push..."

        echo "--- Step 1: Work ID compliance ---"
        devex check-branch
        if [ $? -ne 0 ]; then
            echo "❌ [DevEx Platform] Push aborted due to compliance violations."
            exit 1
        fi

        echo "--- Step 2: Build steps (tests, lint, etc.) ---"
        devex validate
        if [ $? -ne 0 ]; then
            echo "❌ [DevEx Platform] Push aborted due to validation failures."
            exit 1
        fi

        echo "✔ [DevEx Platform] Local validations approved!"
        exit 0
        """
    
    try:
        hook_file.write_text(hook_content, encoding="utf-8")
        
        hook_file.chmod(0o755)
        
        console.print("[green]✔ Git Hook (pre-push) installed successfully![/green]")
        console.print("[blue]ℹ Info:[/blue] Every future `git push` will now automatically enforce your Work ID compliance.")
        raise typer.Exit(code=0)
        
    except typer.Exit:
        raise
    except Exception as e:
        console.print(f"[red]❌ Error configuring the Git Hook:[/red] {str(e)}")
        raise typer.Exit(code=1)