import * as fs from 'node:fs';
import * as path from 'node:path';
import { GitHubWorkflowConfig, AwsCdkConfig, EnvironmentConfig, TestStages } from '../types/index.js';

const DEPLOYMENT_ENV_MAP: Record<string, string> = {
    sandbox: "github.event_name == 'pull_request'",
    staging: "github.ref == 'refs/heads/main'",
    production: "startsWith(github.ref, 'refs/tags/v')",
};

function buildDeploymentSteps(environments: Record<string, EnvironmentConfig>, governance: { requiredApprovals: number }): string {
    return Object.entries(environments).map(([envName, envConfig]) => {
        const condition = DEPLOYMENT_ENV_MAP[envName] || 'github.event_name == \'push\'';
        return `      - name: Deploy to ${envName}
        if: ${condition}
        env:
          AWS_ACCOUNT: ${envConfig.accountId}
          AWS_REGION: ${envConfig.region}
        run: |
          echo "==> [DevEx Platform] Deploying to ${envName} (account: ${envConfig.accountId}, region: ${envConfig.region})..."
          echo "cdk deploy --app 'infra/cdk-stack-${envName}.json' --require-approval never"`;
    }).join('\n');
}

export class DevExGenerator {

    public generateGitHubWorkflow(config: GitHubWorkflowConfig, outputDir: string = '.github/workflows'): string {
        const deploymentSteps = config.environments
            ? buildDeploymentSteps(config.environments, config.governance)
            : '';

        const hasProductionDeploy = config.environments && 'production' in config.environments;

        const smallTestsBlock = config.testStages
            ? this.generateSmallTestsJob(config.testStages)
            : '';

        const workflowYaml = `# ==============================================================================
# AUTOMATICALLY GENERATED BY DEVEX PLATFORM WORKFLOW FRAMEWORK (SOC 2 COMPLIANT)
# TEAM OWNER: ${config.governance.teamOwner}
# TARGET ENVIRONMENT: ${config.environment}
# ==============================================================================

name: ${config.name}

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  compliance-and-build:
    name: Platform Guardrails & Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install DevEx Golden Path CLI
        run: |
          pip install uv
          rm -rf .venv ./devex-cli/.venv
          ${config.cliSource
            ? `pip install "devex-cli@${config.cliSource}"`
            : `uv pip install -e ./devex-cli`}

      - name: Verify Shift-Left Branch Governance
        run: |
          echo "==> [DevEx Platform] Enforcing Work ID compliance checks..."
          devex check-branch

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'
          run_install: false

      ${config.buildSteps.map(step => `- name: Execute Engineering Build Step\n        run: ${step}`).join('\n      ')}

      - name: Enforce Two-Reviewer Rule (SOC 2)
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${'$'}{{ github.token }}
        run: |
          echo "==> [DevEx Platform] Verifying Two-Reviewer approval gate..."
          REVIEWS=$(gh api \\
            "repos/${'$'}{{ github.repository }}/pulls/${'$'}{{ github.event.number }}/reviews" \\
            --jq '[.[] | select(.state == "APPROVED")] | length')
          echo "Approvals found: $REVIEWS (required: ${config.governance.requiredApprovals})"
          if [ "$REVIEWS" -lt ${config.governance.requiredApprovals} ]; then
            echo "❌ [DevEx Platform] Two-Reviewer Rule FAILED. Only $REVIEWS approval(s) found, ${config.governance.requiredApprovals} required."
            exit 1
          fi
          echo "✔ [DevEx Platform] Two-Reviewer Rule satisfied."
${config.aiReview ? `
      - name: Amazon Q Developer Code Review
        if: github.event_name == 'pull_request'
        uses: aws/amazon-q-developer-action@v1
        with:
          github-token: ${'$'}{{ secrets.GITHUB_TOKEN }}
          aws-region: us-east-1
          role-arn: ${'$'}{{ secrets.AWS_Q_ROLE_ARN }}
          analysis-types: security,quality,governance` : ''}

      - name: Emit SOC 2 Compliance Audit Trail
        if: success()
        run: |
          echo "==> [Audit Trail] Verification passed successfully."
          echo "Timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "Team Owner: ${config.governance.teamOwner}"
          echo "Required Reviewers Gate: ${config.governance.requiredApprovals}"
${smallTestsBlock}
  deploy:
    name: Environment Promotion (${'$'}{{ matrix.environment }})
    needs: [ compliance-and-build${config.testStages ? ', small-tests' : ''} ]
    if: ${config.environments ? 'always()' : 'false'}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [${config.environments ? Object.keys(config.environments).join(', ') : ''}]
    environment:
      name: ${'$'}{{ matrix.environment }}
${hasProductionDeploy ? `    concurrency:
      group: ${'$'}{{ matrix.environment }}-deploy
      cancel-in-progress: ${'$'}{{ matrix.environment != 'production' }}` : ''}
    steps:
${deploymentSteps ? `      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Deploy ${'$'}{{ matrix.environment }}
        run: |
          echo "==> [DevEx Platform] Promoting to ${'$'}{{ matrix.environment }}..."
          echo "cdk deploy --app 'infra/cdk-stack-${'$'}{{ matrix.environment }}.json' --require-approval never"` : `      - run: echo "No deployment environments configured"`}
`;

        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const finalPath = path.join(outputDir, 'ci.yml');
        fs.writeFileSync(finalPath, workflowYaml, 'utf-8');

        return finalPath;
    }

    public generatePullRequestTemplate(config: Pick<GitHubWorkflowConfig, 'governance'>, outputDir: string = '.github'): string {
        const templateUrl = `## Description
{WORK_ID}: **Describe your changes here**

## Type of Change
- [ ] New Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Documentation
- [ ] Dependency Update

## DORA Impact
- **Deployment Frequency:**
- **Lead Time for Changes:**
- **Change Failure Rate:**
- **Mean Time to Recovery (MTTR):**

## Testing
- [ ] Unit Tests
- [ ] Integration Tests
- [ ] Manual Tests

## Governance & Audit Trail (SOC 2)
- **Work ID:** {WORK_ID}
- **Team:** ${config.governance.teamOwner}
- **Required Approvals:** ${config.governance.requiredApprovals}
- **Two-Reviewer Rule:** ENFORCED
`;

        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const finalPath = path.join(outputDir, 'PULL_REQUEST_TEMPLATE.md');
        fs.writeFileSync(finalPath, templateUrl, 'utf-8');

        return finalPath;
    }

    private generateSmallTestsJob(testStages: TestStages): string {
        const labelParts = ['Unit'];
        const stepLines: string[] = [
            `      - name: Checkout Source Code
        uses: actions/checkout@v4`,
            `      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'`,
            `      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'
          run_install: false`,
            `      - name: Install Dependencies
        run: pnpm install`,
            `      - name: Unit Tests
        run: ${testStages.unit}`,
        ];

        if (testStages.pbt) {
            labelParts.push('PBT');
            stepLines.push(`      - name: Property-Based Testing
        run: ${testStages.pbt}`);
        }

        if (testStages.contract) {
            labelParts.push('Contract');
            stepLines.push(`      - name: API Contract Validation
        run: ${testStages.contract}`);
        }

        return `
  small-tests:
    name: Small Tests (${labelParts.join(' · ')})
    runs-on: ubuntu-latest
    steps:
${stepLines.join('\n')}
`;
    }

    public generateAwsCdkStack(config: AwsCdkConfig, outputDir: string = 'infra'): string {
        return this.generateAwsCdkStackForEnv(config, undefined, outputDir);
    }

    public generateAwsCdkStackForEnv(config: AwsCdkConfig, envName?: string, outputDir: string = 'infra'): string {
        const cdkPayload = {
            _comment: "AUTOMATICALLY GENERATED BY DEVEX PLATFORM WORKFLOW FRAMEWORK",
            stackName: config.stackName,
            awsMetadata: {
                region: config.region,
                accountId: config.accountId,
            },
            complianceSettings: {
                requiredApprovalsGate: config.governance.requiredApprovals,
                enforceWorkId: config.governance.enforceWorkId,
            },
            resourceTags: {
                Environment: envName || config.environment,
                TeamOwner: config.governance.teamOwner,
                ManagedBy: "DevExGoldenPathFramework",
            },
        };

        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const fileName = envName ? `cdk-stack-${envName}.json` : 'cdk-stack.json';
        const finalPath = path.join(outputDir, fileName);
        fs.writeFileSync(finalPath, JSON.stringify(cdkPayload, null, 2), 'utf-8');

        return finalPath;
    }
}
